name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build with Gradle
      env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          BDUSS: ${{ secrets.BDUSS }}
          FILE_DIR: 音频
          FILE_NAME: 洛天依-腐乘以无限大.mp3
      run: |
          chmod 777 ./app/post.sh
          ./app/post.sh
